name: Build Android Release APK

on:
  push:
    branches:
      - main   # 或者你想触发的分支
  workflow_dispatch:  # 手动触发

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    steps:
      # 1️⃣ 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 设置 JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ 缓存 Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      # 4️⃣ 安装 Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2
          target: android-33
          ndk: 25.2.9519653  # 可选，如果需要 NDK

      # 5️⃣ 打包 Release APK
      - name: Build Release APK
        run: ./gradlew clean assembleRelease --stacktrace

      # 6️⃣ 上传 APK 作为 artifact
      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk